# Generated by Django 5.0 on 2025-11-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_eventcategory_options_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_tag',
            field=models.CharField(choices=[('paid', 'Paid'), ('free', 'Free')], default='', max_length=10, null=True),
        ),
    ]
