# Generated by Django 5.0 on 2025-12-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_tickets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
