# Generated by Django 5.0 on 2025-12-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_event_available_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='creator',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
