# Generated by Django 5.0 on 2025-12-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_organizer_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='creator',
            field=models.BooleanField(default=False),
        ),
    ]
