# Generated by Django 5.0 on 2025-12-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_event_available_tickets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='available_tickets',
            new_name='purchased_tickets',
        ),
    ]
