# Generated by Django 5.0 on 2025-12-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_available_tickets_event_purchased_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='purchased_tickets',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
