# Generated by Django 5.0 on 2025-12-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_event_purchased_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_past',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
