# Generated by Django 5.0 on 2025-12-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_event_is_past'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_past',
            field=models.BooleanField(default=False),
        ),
    ]
