# Generated by Django 5.0 on 2025-12-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_event_is_past'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_past',
        ),
    ]
