# Generated by Django 5.0 on 2025-12-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_likedevent_event_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='momo_numb',
        ),
    ]
