# Generated by Django 5.0 on 2025-12-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_organizer_momo_numb'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='momo_numb',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
