# Generated by Django 5.0 on 2025-12-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_organizer_momo_numb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='momo_numb',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
