# Generated by Django 5.0 on 2025-12-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_organizer_momo_numb'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
