# Generated by Django 5.0 on 2026-01-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
