# Generated by Django 5.0 on 2026-01-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_event_organizer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer_name',
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
