# Generated by Django 5.0 on 2026-01-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('upcoming', 'Upcoming'), ('past', 'Past')], default='', max_length=10, null=True),
        ),
    ]
