# Generated by Django 5.0 on 2026-01-29 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_event_payment_status_event_status'),
        ('payment', '0006_freeeventregisterinfo_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payment'),
        ),
    ]
