# Generated by Django 5.0 on 2025-11-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeeventregisterinfo',
            name='contact',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
