# Generated by Django 5.0 on 2025-12-18 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freeeventregisterinfo',
            name='event',
        ),
    ]
