# Generated by Django 5.0 on 2025-12-18 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_event_is_past'),
        ('payment', '0005_remove_freeeventregisterinfo_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeeventregisterinfo',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.event'),
        ),
    ]
